"""Pure starter MIDI exercise generators."""

from __future__ import annotations

import struct
from dataclasses import dataclass
from typing import Iterable, Sequence

PPQ = 480
GENERATOR_TEXT = "Generated by tools/generate_midi.py"


@dataclass(frozen=True)
class Note:
    start: int
    duration: int
    pitch: int
    velocity: int = 84
    channel: int = 0


@dataclass(frozen=True)
class ControlChange:
    tick: int
    controller: int
    value: int
    channel: int = 0


Event = tuple[int, bytes]


def vlq(value: int) -> bytes:
    if value < 0:
        raise ValueError("VLQ cannot encode negative values")
    buffer = value & 0x7F
    value >>= 7
    while value:
        buffer <<= 8
        buffer |= (value & 0x7F) | 0x80
        value >>= 7

    out = bytearray()
    while True:
        out.append(buffer & 0xFF)
        if buffer & 0x80:
            buffer >>= 8
        else:
            break
    return bytes(out)


def meta_text(kind: int, text: str) -> bytes:
    payload = text.encode("utf-8")
    return bytes([0xFF, kind]) + vlq(len(payload)) + payload


def tempo_event(bpm: int) -> bytes:
    micros_per_quarter = round(60_000_000 / bpm)
    return b"\xFF\x51\x03" + micros_per_quarter.to_bytes(3, "big")


def program_change(channel: int, program: int) -> bytes:
    return bytes([0xC0 | channel, program & 0x7F])


def note_on(note: Note) -> bytes:
    return bytes([0x90 | note.channel, note.pitch & 0x7F, note.velocity & 0x7F])


def note_off(note: Note) -> bytes:
    return bytes([0x80 | note.channel, note.pitch & 0x7F, 0])


def cc(event: ControlChange) -> bytes:
    return bytes(
        [
            0xB0 | event.channel,
            event.controller & 0x7F,
            event.value & 0x7F,
        ]
    )


def track_chunk(events: Iterable[Event]) -> bytes:
    ordered = sorted(events, key=lambda item: item[0])
    payload = bytearray()
    previous_tick = 0
    for tick, data in ordered:
        if tick < previous_tick:
            raise ValueError("Events must not move backwards in time")
        payload += vlq(tick - previous_tick)
        payload += data
        previous_tick = tick
    payload += vlq(0)
    payload += b"\xFF\x2F\x00"
    return b"MTrk" + struct.pack(">I", len(payload)) + bytes(payload)


def midi_file(tracks: Sequence[bytes]) -> bytes:
    header = b"MThd" + struct.pack(">IHHH", 6, 1, len(tracks), PPQ)
    return header + b"".join(tracks)


def notes_to_events(notes: Iterable[Note]) -> list[Event]:
    events: list[Event] = []
    for note in notes:
        events.append((note.start, note_on(note)))
        events.append((note.start + note.duration, note_off(note)))
    return events


def meta_track(title: str, bpm: int) -> bytes:
    return track_chunk(
        [
            (0, meta_text(0x03, title)),
            (0, tempo_event(bpm)),
            (0, meta_text(0x01, GENERATOR_TEXT)),
        ]
    )


def instrument_track(
    name: str,
    program: int,
    notes: Sequence[Note],
    ccs: Sequence[ControlChange] = (),
) -> bytes:
    events: list[Event] = [
        (0, meta_text(0x03, name)),
        (0, program_change(0, program)),
    ]
    events.extend(notes_to_events(notes))
    events.extend((event.tick, cc(event)) for event in ccs)
    return track_chunk(events)


def drum_track(name: str, notes: Sequence[Note]) -> bytes:
    events: list[Event] = [(0, meta_text(0x03, name))]
    events.extend(notes_to_events(notes))
    return track_chunk(events)


def muted_16th_warmup(bpm: int, bars: int) -> bytes:
    sixteenth = PPQ // 4
    notes: list[Note] = []
    for step in range(bars * 16):
        accent = step % 8 in {0, 4}
        notes.append(Note(step * sixteenth, sixteenth // 2, 60, 96 if accent else 56))

    drums: list[Note] = []
    for beat in range(bars * 4):
        tick = beat * PPQ
        drums.append(Note(tick, 60, 42, 48, channel=9))
        if beat % 4 in (1, 3):
            drums.append(Note(tick, 80, 38, 88, channel=9))
        else:
            drums.append(Note(tick, 80, 36, 78, channel=9))

    return midi_file(
        [
            meta_track("Muted 16th Warmup", bpm),
            instrument_track("Muted guide notes", 27, notes),
            drum_track("Simple pulse", drums),
        ]
    )


def wah_accent_groove(bpm: int, bars: int) -> bytes:
    sixteenth = PPQ // 4
    guide: list[Note] = []
    sweep: list[ControlChange] = []
    accent_steps = {0, 3, 6, 10, 12}
    for step in range(bars * 16):
        bar_step = step % 16
        tick = step * sixteenth
        if bar_step in accent_steps:
            guide.append(Note(tick, sixteenth, 57, 104))
            sweep.append(ControlChange(tick, 11, 110))
            sweep.append(ControlChange(tick + sixteenth // 2, 11, 45))
        elif bar_step in {4, 8}:
            guide.append(Note(tick, sixteenth // 2, 57, 52))

    bass = [Note(bar * 4 * PPQ, PPQ * 2, 45, 76) for bar in range(bars)]
    return midi_file(
        [
            meta_track("Wah Accent Groove", bpm),
            instrument_track("Accent cues", 27, guide, sweep),
            instrument_track("Bass drone", 33, bass),
        ]
    )


def u2_delay_pulse(bpm: int, bars: int) -> bytes:
    eighth = PPQ // 2
    pitches = [64, 71, 76, 71, 66, 73, 78, 73]
    notes: list[Note] = []
    for step in range(bars * 8):
        pitch = pitches[step % len(pitches)]
        velocity = 92 if step % 3 == 0 else 70
        notes.append(Note(step * eighth, eighth, pitch, velocity))
    root = [Note(bar * 4 * PPQ, 4 * PPQ, 40, 54) for bar in range(bars)]
    return midi_file(
        [
            meta_track("U2-Style Delay Pulse", bpm),
            instrument_track("Arpeggio guide", 29, notes),
            instrument_track("Root bed", 88, root),
        ]
    )


def minor_pentatonic_call_response(bpm: int, bars: int) -> bytes:
    quarter = PPQ
    scale = [57, 60, 62, 64, 67, 69]
    notes: list[Note] = []
    for bar in range(bars):
        base = bar * 4 * PPQ
        if bar % 4 in (0, 1):
            phrase = [0, 2, 3, 2] if bar % 4 == 0 else [4, 3, 2]
            for index, scale_index in enumerate(phrase):
                notes.append(
                    Note(base + index * quarter, quarter // 2, scale[scale_index], 88)
                )
        else:
            notes.append(Note(base + 3 * quarter, quarter // 2, scale[0], 42))
    return midi_file(
        [
            meta_track("Minor Pentatonic Call and Response", bpm),
            instrument_track("Phrase cues", 26, notes),
        ]
    )


def bend_intonation_drone(bpm: int, bars: int) -> bytes:
    whole = 4 * PPQ
    drone = [Note(0, bars * whole, 57, 48)]
    targets: list[Note] = []
    for bar in range(bars):
        tick = bar * whole
        targets.append(Note(tick + PPQ, PPQ, 62, 82))
        targets.append(Note(tick + 3 * PPQ, PPQ // 2, 64, 72))
    return midi_file(
        [
            meta_track("Bend Intonation Drone", bpm),
            instrument_track("A drone", 88, drone),
            instrument_track("Target pitch cues", 26, targets),
        ]
    )


GENERATORS = {
    "muted_16th_warmup": muted_16th_warmup,
    "wah_accent_groove": wah_accent_groove,
    "u2_delay_pulse": u2_delay_pulse,
    "minor_pentatonic_call_response": minor_pentatonic_call_response,
    "bend_intonation_drone": bend_intonation_drone,
}


def generate_exercise(exercise: dict) -> bytes:
    exercise_id = exercise.get("id")
    generator = GENERATORS.get(exercise_id)
    if generator is None:
        raise KeyError(f"No generator registered for {exercise_id}")
    bpm = exercise.get("bpm")
    bars = exercise.get("bars")
    if isinstance(bpm, bool) or not isinstance(bpm, int) or bpm <= 0:
        raise ValueError("exercise.bpm must be a positive integer")
    if isinstance(bars, bool) or not isinstance(bars, int) or bars <= 0:
        raise ValueError("exercise.bars must be a positive integer")
    return generator(bpm, bars)
